### ISSUE TITLE
Problem with GetHTTPValues

### ISSUE THREAD

**Issue by FifasCat** [kovi44/m5paper-PV-dashboard#1]
Hi, thank you for your big work. I'm have problems withe the code. 
When the program go to the FusionsolaR kiosk the answer don't have any  values. Could be the problems because mi fusionsolar adress start with https:\\ ?? In your proyect is only with http. Thanyou for you time and your work.

**Comment by kovi44** [comment]
Hi, please see my other project, which can be found here https://github.com/kovi44/m5paper-Huawei-sun2000-kiosk - this one is working with kiosk mode. If you prefer pv dashboard instead then you need a mediation script which translate modbustcp to suitable form for this integration. These days i am working on dashboard which works without mediation script directly with huawei openapi

**Comment by FifasCat** [comment]
Thanks for the speed. I try with the other program but don't work. Only one question. My board is LilyGo-EPD47, I can see that the Init and others are diferents for M5. Do you think that the problem is this?. Thnak you.

**Comment by kovi44** [comment]
The code is for m5paper. I am not familiar with LillyGo. I used som libraries which are only for this board.
